### ISSUE TITLE
Correct "official" version: Latest here or version at unidata.ucar.edu?

### ISSUE THREAD

**Issue by mathomp4** [Unidata/UDUNITS-2#101]
All,

This is just a query. I'm wondering, where should I look for new versions of UDUNITS-2 when I think "Should I update UDUNITS-2"? 

I used to/still go to https://www.unidata.ucar.edu/downloads/udunits/ but that seems to still be at 2.2.26 which is a few years old. On this site I see many a tag (2.2.27.27 is the latest) but none of them "look" like "official GitHub" releases a la the fancy ones like https://github.com/Unidata/netcdf-c/releases/tag/v4.7.4 by @WardF. And the tags come out fast, so I'm a bit scared to try and keep up. 😄

**Comment by semmerson** [comment]
2.2.27.27 isn't a release: it's an artifact of GitHub interpreting tagged commits as releases.

I'm working on making a 2.2.27 release. It's a bit complicated and taking longer than usual because we've stopped using Travis CI (because they've instituted institutional quotas) and because we're moving to a Nexus distribution server.
