### ISSUE TITLE
incorrect acres to ft^2 conversion

### ISSUE THREAD

**Issue by iembry** [Unidata/UDUNITS-2#56]
Hi, according to [Units and Symbols Found in the UDUNITS2 Database](https://ncics.org/portfolio/other-resources/udunits2/), an acre is

> unit of area in the US Customary System, used in land and sea floor measurement, equal to 43560 square feet (exact).

If that is true, then the following is incorrect:

```
library(units)

ad <- with(ud_units, 1 * acre)

ad
1 acre


units(ad) <- with(ud_units, ft^2)

ad
43560.17 ft^2
```

If the current definition of acres is incorrect within `units`, then will you correct it then?

Thank you.

Irucka Embry

**Comment by gregor-fausto** [comment]
Adding to this issue. In the UDUNITS2 documentation here https://docs.unidata.ucar.edu/udunits/current/udunits2-common.xml the following definition is given for acre:

> **acre**: unit of area in the US Customary System, used in land and sea floor measurement, equal to 43560 square feet

**Comment by WardF** [comment]
Thank you, I'll take a look at this!

**Comment by WardF** [comment]
The issue appears to be in the conversion to acre->rod^2->ft^2.  I will continue to look into this.

**Comment by WardF** [comment]
```
./udunits2 -H "1 rod^2" -W ft^2
    1 rod^2 = 272.251 ft^2
    x/ft^2 = 272.251*(x/rod^2)
```

It appears there is an issue going on here related to floating point arithmetic.

**Comment by dopplershift** [comment]
So following the chain above and stopping at m^2:
```
1 * 160 * 16.5**2 * (1200 / 3937) **2
```
gives `4046.8726098742513`, which matches the [defintion from NIST](https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b8) of `4.046 873	E+03` to 7 figures.

@iembry I think the real problem here is a confusion where asking for `ft` converts to "international foot". If you want the exact 43560 value, you need to do: `units(ad) <- with(ud_units, us_suvey_foot^2)`

**Comment by WardF** [comment]
Thanks @dopplershift for the clarification and also for beating me to the punch, the issue here is 'what type' of foot. @gregor-fausto you will want to specify `us_survey_foot` as @dopplershift alludes to.

Thanks to my ESS colleagues @dopplershift and @ThomasMGeo for helping me track this down.
